import {
  SlashCommandBuilder,
  EmbedBuilder,
  type ChatInputCommandInteraction,
} from "discord.js";
import LicenseModel from "../../models/License";
import { generateLicenseKey, calculateExpiry } from "../../lib/keyGenerator";
import type { BotCommand } from "../index";

const PLAN_DURATIONS: Record<string, number | null> = {
  "7d": 7,
  "30d": 30,
  "lifetime": null,
};

const command: BotCommand = {
  data: new SlashCommandBuilder()
    .setName("genkey")
    .setDescription("Generate one or more license keys")
    .addStringOption((opt) =>
      opt
        .setName("plan")
        .setDescription("License plan")
        .setRequired(true)
        .addChoices(
          { name: "Basic", value: "basic" },
          { name: "Premium", value: "premium" },
          { name: "Lifetime", value: "lifetime" },
        ),
    )
    .addStringOption((opt) =>
      opt
        .setName("duration")
        .setDescription("Key duration")
        .setRequired(true)
        .addChoices(
          { name: "7 Days", value: "7d" },
          { name: "30 Days", value: "30d" },
          { name: "Lifetime", value: "lifetime" },
        ),
    )
    .addIntegerOption((opt) =>
      opt.setName("quantity").setDescription("Number of keys to generate (1-10)").setMinValue(1).setMaxValue(10),
    )
    .addStringOption((opt) => opt.setName("notes").setDescription("Optional notes for this key")),

  async execute(interaction: ChatInputCommandInteraction): Promise<void> {
    await interaction.deferReply({ ephemeral: true });

    const plan = interaction.options.getString("plan", true) as "basic" | "premium" | "lifetime";
    const duration = interaction.options.getString("duration", true);
    const quantity = interaction.options.getInteger("quantity") ?? 1;
    const notes = interaction.options.getString("notes");

    const durationDays = PLAN_DURATIONS[duration];
    const keys: string[] = [];

    for (let i = 0; i < quantity; i++) {
      let key: string;
      let exists = true;
      do {
        key = generateLicenseKey();
        const existing = await LicenseModel.findOne({ key });
        exists = !!existing;
      } while (exists);

      const expiresAt = calculateExpiry(durationDays);
      await LicenseModel.create({
        key,
        status: "pending",
        plan,
        durationDays,
        expiresAt,
        createdBy: interaction.user.id,
        createdByUsername: interaction.user.username,
        notes: notes || null,
      });
      keys.push(key);
    }

    const embed = new EmbedBuilder()
      .setColor(0x5865f2)
      .setTitle(`✅ Generated ${quantity} License Key${quantity > 1 ? "s" : ""}`)
      .addFields(
        { name: "Plan", value: plan.charAt(0).toUpperCase() + plan.slice(1), inline: true },
        { name: "Duration", value: duration === "lifetime" ? "Lifetime" : `${durationDays} Days`, inline: true },
        { name: "Generated By", value: `<@${interaction.user.id}>`, inline: true },
        { name: "Keys", value: keys.map((k) => `\`${k}\``).join("\n") },
      )
      .setTimestamp();

    if (notes) embed.addFields({ name: "Notes", value: notes });

    await interaction.editReply({ embeds: [embed] });
  },
};

export default command;
